name: Node.js Package
on: push
jobs:
  build:
    name: test & lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      - run: npm run lint --if-present
      - run: npm test --if-present

  npm-publish:
    name: build & publish
    needs: build
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - name: Build JS and DTS to /dist
        run: npm run build --if-present
      - name: Publish if version has been updated
        uses: pascalgn/npm-publish-action@1.3.9
        with:
          commit_pattern: "^(?:[\\w\\d]+\\s+)?(?:v?)(\\S+)"
          publish_args: "--non-interactive"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
